comments/urls.py
from django.urls import path

from comments import views

app_name = "comments"
urlpatterns = [
    path("submit_comment", views.submit_comment, name="submit_comment"),
    path("approve/<str:approve_key>", views.approve_comment, name="approve_comment"),
]

dfb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from django_summernote.views import SummernoteUploadAttachment


admin.site.site_title = "DFB Admin"
admin.site.site_header = "DFB Admin"

urlpatterns = [
    path("", include("pages.urls"), name="pages"),
    path("biographies/", include("biographies.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("images/", include("images.urls")),
    path("authors/", include("authors.urls")),
    path("comments/", include("comments.urls")),
    path("admin/", admin.site.urls),
    # dirty fix, needed for django-summernote to work with attachments disabled
    path(
        "summernote/upload_attachment/",
        SummernoteUploadAttachment.as_view(),
        name="django_summernote-upload_attachment",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
import secrets

from django.db import models

from biographies.models import Biography


class Comment(models.Model):
    biography = models.ForeignKey(
        Biography, on_delete=models.CASCADE, related_name="comments"
    )
    name = models.CharField(help_text="Name displayed with the comment (required).")
    email = models.EmailField(
        null=False, help_text="This will not be displayed publically (required)."
    )
    comment = models.TextField(null=False)
    approved = models.BooleanField(default=False)
    approve_key = models.CharField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def set_approve_key(self):
        self.approve_key = secrets.token_urlsafe(16)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.comment[:20]}..."

comments/forms.py
from django import forms

from comments.models import Comment


class SubmitCommentForm(forms.ModelForm):
    url = forms.CharField(initial="", required=False)

    class Meta:
        model = Comment
        fields = ["name", "email", "comment", "biography", "url"]
        widgets = {"biography": forms.HiddenInput()}

comments/views.py
from urllib.parse import urljoin

from django.urls import reverse
from django.http import JsonResponse
from django.shortcuts import render

from comments.forms import SubmitCommentForm
from comments.tasks import send_user_email, send_admin_email
from comments.models import Comment


def approve_link(request, comment):
    """Generate a app link for the agreement"""

    base_url = request.build_absolute_uri("/")
    approve_url = reverse("comments:approve_comment", args=[comment.approve_key])
    return urljoin(base_url, approve_url)


def submit_comment(request):
    if request.method == "POST":
        form = SubmitCommentForm(request.POST)
        if form.is_valid():
            if form.data["url"] == "":
                comment = form.instance
                comment.set_approve_key()
                comment.save()
                send_user_email.delay_on_commit(comment.id)
                send_admin_email.delay_on_commit(
                    comment.id, approve_link(request, comment)
                )
                data = {"status": "success"}
                status = 200
            else:
                data = {"status": "success_"}
                status = 200
        else:
            data = {"status": "data-error", "errors": form.errors.as_json()}
            status = 400
    else:
        data = {"status": "method-error"}
        status = 405

    return JsonResponse(data, status=status)


def approve_comment(request, approve_key):
    try:
        comment = Comment.objects.get(approve_key=approve_key)
        comment.approved = True
        comment.approve_key = None
        comment.save()
        context = {
            "heading": "Comment Approved",
            "message": "Thank you for approving the comment. It is now visible on the biography page.",
        }
    except Comment.DoesNotExist:
        context = {"heading": "Approval Failed", "message": "Invalid approval key."}

    return render(request, "comments/approve_result.html", context)

comments/templates/comments/_comments.html
<div class="biography_comments_wrapper">
    <h4><strong>Comments</strong></h4>
    {% if biography.approved_comments %}
        {% for comment in biography.approved_comments %}
            <div class="card ml-3 mb-3">
                <div class="card-body bg-light">
                    <h5 class="card-title">{{ comment.name }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ comment.created_at }}</h6>
                    <p class="card-text"> {{ comment.comment|linebreaksbr }}</p>
                </div>
            </div>    
        {% endfor %}
    {% endif %}
    <button id="comment_button" type="button" class="btn btn-outline-dark ml-3 mb-2" data-toggle="modal" data-target="#comments-form-modal">
        Add comment
    </button>
</div>

comments/templates/comments/_comments_modal_form.html
{%load crispy_forms_tags %} 

<script type="text/javascript">
    var commentSubmitUrl = "{% url 'comments:submit_comment' %}";
</script>

<div id="comments-form-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Comment</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form id="comment_form" method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" value="Leave Comment" class="btn btn-outline-dark">
                </form>
                <div id="comment_success">
                    <h3>Submitted</h3>
                    <p>Please note, comments are reviewed by the web editor before appearing on the site.
                        This process may take up to 3 days. Email <a target="_blank" href="mailto:webeditor@falklandsbiographies.org">
                        webeditor@falklandsbiographies.org</a> for further information.
                    </p>
                </div>
                <div id="comment_failure">
                    <h3>Error</h3>
                    <p>Comment submission failed. Please try again or contact <a target="_blank" href="mailto:webeditor@falklandsbiographies.org">
                       webeditor@falklandsbiographies.org</a> for assistance.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

comments/templates/comments/approve_result.html
{% extends "common/base.html" %}
{% block home_page %}

    <div class="container w-80 pt-3">
    <h3>{{ heading }}</h3>
        <p>{{ message }}</p>
    </div>

{% endblock %}