authors/urls.py
from django.urls import path

from authors.views import AuthorsListView

app_name = "authors"
urlpatterns = [path("", AuthorsListView.as_view(), name="index")]

biographies/urls.py
from django.urls import path

from .views import index, show_by_slug, show_by_id

app_name = "biographies"
urlpatterns = [
    path("", index, name="index"),
    path("<int:bio_id>", show_by_id, name="show_by_id"),
    path("<slug:bio_slug>", show_by_slug, name="show"),
]

dfb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from django_summernote.views import SummernoteUploadAttachment


admin.site.site_title = "DFB Admin"
admin.site.site_header = "DFB Admin"

urlpatterns = [
    path("", include("pages.urls"), name="pages"),
    path("biographies/", include("biographies.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("images/", include("images.urls")),
    path("authors/", include("authors.urls")),
    path("comments/", include("comments.urls")),
    path("admin/", admin.site.urls),
    # dirty fix, needed for django-summernote to work with attachments disabled
    path(
        "summernote/upload_attachment/",
        SummernoteUploadAttachment.as_view(),
        name="django_summernote-upload_attachment",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authors/models.py
from django.db import models
from django.utils.text import slugify

from biographies.models import Biography


class Author(models.Model):
    first_name = models.CharField(blank=True, null=True)
    last_name = models.CharField()
    biography = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("first_name", "last_name")
        ordering = ["last_name", "first_name"]

    @property
    def name(self):
        formatted_first_name = f"{self.first_name} " if self.first_name else ""
        return formatted_first_name + self.last_name

    @property
    def simple_slug(self):
        return slugify(self.name)

    def __str__(self):
        formatted_first_name = f", {self.first_name}" if self.first_name else ""
        return self.last_name + formatted_first_name

    @property
    def short_biography(self):
        if not self.biography:
            return "No biography available."

        if len(self.biography) > 100:
            return self.biography[:100] + "..."
        return self.biography


class BiographyAuthor(models.Model):
    biography = models.ForeignKey(Biography, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    author_position = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = [("biography", "author"), ("biography", "author_position")]
        ordering = ["author_position"]

    def __str__(self):
        return f"#{self.id}"

authors/views.py
from django.views.generic import ListView
from authors.models import Author


class AuthorsListView(ListView):
    model = Author

authors/templates/authors/_authors_modal.html
<!-- Authors modal -->
<div id="authors-info" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Authors</h5>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
        {% for author in authors %}
            <h4><strong>{{ author.name }}</strong></h4>
            {% if author.biography %}
                <p>{{ author.biography }}</p>
            {% endif %}
            <small><ul>
            {% for biography in author.biographies.all|slice:":3" %}
                <li>
                    <a href="{% url 'biographies:show' bio_slug=biography.slug %}" >{{ biography.title }}</a>
                    {% if biography.get_authors.count > 1 %}
                        <ul class="other-authors-list">
                            {% for other_author in biography.get_authors %}
                                {% if other_author != author %}
                                <li class="other-authors-list-item">with
                                    <a class="font-italic" href="{% url 'authors:index' %}#{{author.simple_slug}}">
                                        {{ other_author.name }}
                                    </a>
                                </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
            {% endfor %}
            {% if author.biographies.all.count > 3 %}
                <li class="more-link"><a href="{% url 'authors:index' %}#{{ author.simple_slug }}" class="more-link">more...</a></li>
            {% endif %}
            </ul></small>
            {% if author != biography.get_authors.last %}
                <hr>
            {% endif %}
        {% endfor %}
        </div>
        </div>
    </div>
</div>

authors/templates/authors/author_list.html
{% extends "common/base.html" %}
{% load static %}

{% block app_js %}
    <script src="https://cdn.jsdelivr.net/npm/jquery.scrollto@2.1.3/jquery.scrollTo.min.js"></script>
    <script src="{% static 'js/authors.js' %}"></script>
{% endblock %}

{% block content %}

<h3>
  <strong>Authors</strong>
</h3>

<div class="card-columns custom-columns">
    {% for author in object_list %}
        <div class="card">
            <div class="card-body">
                <span class="anchor" id="{{ author.simple_slug}}"></span>
                <h5 class="card-title">{{ author.name }}</h5>
                {% if author.biography %}
                    <p class="card-text">{{author.biography}}</p>
                {% endif %}
                <hr>
                <small>
                <ul class="bios-list">
                    {% for biography in author.biographies.all %}
                    <li class="bios-list-item">
                        <a class="card-link" href="{% url 'biographies:show' bio_slug=biography.slug %}">{{ biography.title }}</a>
                        {% if biography.authors_connections.all.count > 1 %}
                            <ul class="other-authors-list">
                                {% for auth_conn in biography.authors_connections.all %}
                                    {% if auth_conn != author %}
                                    <li class="other-authors-list-item">with
                                        <span class="card-link font-italic author-link" data-hash="{{auth_conn.simple_slug}}">
                                            {{ auth_conn.name }}
                                        </span>
                                    </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
                </small>
            </div>
        </div>
    {% empty %}
        <div class="item">
            No authors
        </div>
    {% endfor %}
</div>


{% endblock %}