authors/urls.py
from django.urls import path

from authors.views import AuthorsListView

app_name = "authors"
urlpatterns = [path("", AuthorsListView.as_view(), name="index")]

biographies/urls.py
from django.urls import path

from .views import index, show_by_slug, show_by_id

app_name = "biographies"
urlpatterns = [
    path("", index, name="index"),
    path("<int:bio_id>", show_by_id, name="show_by_id"),
    path("<slug:bio_slug>", show_by_slug, name="show"),
]

dfb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from django_summernote.views import SummernoteUploadAttachment


admin.site.site_title = "DFB Admin"
admin.site.site_header = "DFB Admin"

urlpatterns = [
    path("", include("pages.urls"), name="pages"),
    path("biographies/", include("biographies.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("images/", include("images.urls")),
    path("authors/", include("authors.urls")),
    path("comments/", include("comments.urls")),
    path("admin/", admin.site.urls),
    # dirty fix, needed for django-summernote to work with attachments disabled
    path(
        "summernote/upload_attachment/",
        SummernoteUploadAttachment.as_view(),
        name="django_summernote-upload_attachment",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.home, name="home"),
    path("<slug:page_slug>", views.show, name="show"),
]

common/templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

{% include "./favicon.html" %}

{% if env == 'production' %}
    <title>DFB</title>
{% else %}
    <title>DFB - {{ ENVIRONMENT|title }} </title>
{% endif %}
{% load compress %}

{% compress css %}
<link type="text/x-scss" href="{% static 'css/base.scss' %}" rel="stylesheet" media="screen">
{% endcompress %}

{% block app_css %}{% endblock %}


<script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
{% block app_js %}{% endblock %}

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

</head>
<body>

{% include "./navbar.html" %}

<div class="container-flex" style="margin-top:72px"></div>

{% block home_page %}{% endblock %}
<div class="container py-3">
    {% block content %}{% endblock %}
</div> 

{% include "./footer.html" %}

</body>
</html>

common/templates/common/favicon.html
{% load static %}

<link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'images/favicon/manifest.json' %}">
<link rel="mask-icon" href="{% static 'images/favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
<link rel="shortcut icon" href="{% static 'images/favicon/favicon.ico' %}">
<meta name="msapplication-config" content="{% static 'images/favicon/browserconfig.xml' %}">
<meta name="theme-color" content="#ffffff">

common/templates/common/footer.html
<footer class="page-footer font-small bg-secondary">
    <div class="footer-copyright text-center py-3 text-light">
        &copy; {{ COPYRIGHT }} David Tatham. All rights reserved.<br>
        <a href="{% url 'admin:index' %}" class="text-light"><small>Admin Login</small></a>
    </div>
</footer>

common/templates/common/navbar.html
<header>
  <nav class="navbar navbar-expand-md bg-primary navbar-dark fixed-top">
    <div class="container">
      <!-- Brand -->

      <a class="navbar-brand d-none d-lg-block" href="#">Dictionary of Falklands Biography</a>
      <a class="navbar-brand d-block d-sm-block d-lg-none" href="#">Falklands Biography</a>

      <!-- Toggler/collapsibe Button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <i class="fa fa-bars"></i>
      </button>

      <!-- Menu -->
      <div class="collapse navbar-collapse  justify-content-end" id="collapsibleNavbar">
        <ul class="navbar-nav text-uppercase">

          <!--Home-->
          <li class="nav-item"><a href="/" class="nav-link" %>Home</a></li>

          <!--Biographies-->
          <li class="nav-item"><a href="{% url 'biographies:index' %}" class="nav-link" %>Biographies</a></li>

          <!--About Menu-->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="navbardrop" href="#">About</a>
            <div class="dropdown-menu shadow">
              <a  href="{% url 'pages:show' 'about' %}" class="dropdown-item">About DFB</a>
              <a  href="{% url 'pages:show' 'falklands_story' %}" class="dropdown-item">The Falklands Story</a>
              <a  href="{% url 'authors:index' %}" class="dropdown-item">Authors</a>
              <a  href="{% url 'pages:show' 'jane_cameron' %}" class="dropdown-item">Jane Cameron - Obituary</a>
              <div class="dropdown-divider"></div>
              <a  href="{% url 'pages:show' 'book_foreword' %}" class="dropdown-item">Foreword</a>
              <a  href="{% url 'pages:show' 'book_introduction' %}" class="dropdown-item">Introduction</a>
              <a  href="{% url 'pages:show' 'book_acknowledgements' %}" class="dropdown-item">Acknowledgements</a>
              <a  href="{% url 'pages:show' 'book_david_tatham' %}" class="dropdown-item">David Tatham</a>
              <a  href="{% url 'pages:show' 'book_reviews' %}" class="dropdown-item">Reviews</a>
              <a  href="{% url 'pages:show' 'book_purchase' %}" class="dropdown-item">How to buy</a>
            </div>
          </li>

          <!--Contacts-->
          <li class="nav-item"><a href="{% url 'pages:show' 'contacts' %}" class="nav-link" %>Contacts</a></li>

        </ul>
      </div>
    </div><!--container-->
  </nav>
</header>